/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tristan_image_process_demo_ImageProcessActivity */

#ifndef _Included_com_tristan_image_process_demo_ImageProcessActivity
#define _Included_com_tristan_image_process_demo_ImageProcessActivity
#ifdef __cplusplus
extern "C" {
#endif
#undef com_tristan_image_process_demo_ImageProcessActivity_REQUEST_CODE
#define com_tristan_image_process_demo_ImageProcessActivity_REQUEST_CODE 1L
/*
 * Class:     com_renren_image_process_demo_ImageProcessActivity
 * Method:    testLib
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_renren_image_process_demo_ImageProcessActivity_testLib
  (JNIEnv *, jobject);

/*
 * Class:     com_renren_image_process_demo_ImageProcessActivity
 * Method:    processImage
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_renren_image_process_demo_ImageProcessActivity_processImage
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
